# Generated by Django 5.1.2 on 2024-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True)),
                ('amount_to_pay', models.IntegerField(blank=True)),
                ('payment_for_the_month_of', models.DateField(blank=True)),
                ('date_paid', models.DateField(blank=True)),
            ],
        ),
    ]
